
 //----------------------------------------------
 //
 //        Sketch Generated by Visuino
 //              www.visuino.com
 //          Version 7.8.3.60
 //
 //------------------ Source --------------------
 //
 // LCDARDUINO.visuino
 //
 //----------------------------------------------

#define VISUINO_ARDUINO_UNO

#include <OpenWire.h>
#include <Mitov.h>
#include <Mitov_LiquidCrystalDisplay.h>

// Shared Component Member Variables

namespace ComponentVariables
{
class
{
public:
  uint32_t Value1 : 5;
  uint32_t Value2 : 2;

} BitFields;

class Variable1
{
public:
  inline static uint32_t GetValue() { return BitFields.Value1; }
  inline static void SetValue( uint32_t AValue ) { BitFields.Value1 = AValue; }

};
class Variable2
{
public:
  inline static uint32_t GetValue() { return BitFields.Value2; }
  inline static void SetValue( uint32_t AValue ) { BitFields.Value2 = AValue; }

};
} // ComponentVariables

// Arduino Constant Declarations

namespace VisuinoConstants
{
class TextValue0
{
public:
    inline static constexpr const char *GetValue() { return "Hola Mundo"; }
};

} // VisuinoConstants

// Declarations

namespace Declarations
{
Mitov::LiquidCrystalDisplay<
  Mitov::LiquidCrystalDisplayParallel<
  Mitov::LiquidCrystalDisplayParallel4DataPins<Mitov::DigitalPin_DirectBoardPinImplementation<4 >, Mitov::DigitalPin_DirectBoardPinImplementation<5 >, Mitov::DigitalPin_DirectBoardPinImplementation<6 >, Mitov::DigitalPin_DirectBoardPinImplementation<7 >>, // 1_PINS
  Mitov::DigitalPin_DirectBoardPinImplementation<8 >, // 1_PINS_0
  Mitov::DigitalPin_NoImplementation<1 >, // 1_PINS_1
  Mitov::DigitalPin_DirectBoardPinImplementation<9 >, // 1_PINS_2
  Mitov::ConstantProperty<21, bool, false >, // AutoScroll
  Mitov::ConstantProperty<24, bool, false >, // Blink
  Mitov::ConstantProperty<20, bool, true >, // Enabled
  Mitov::ConstantProperty<25, bool, false >, // Hight10Pixels
  Mitov::ConstantProperty<22, bool, false >, // RightToLeft
  Mitov::ConstantProperty<23, bool, false > // ShowCursor
  >, // 0_TYPE
  16, // Columns
  Mitov::TypedVariable<38, uint32_t, ::ComponentVariables::Variable2>, // FCursorLine
  Mitov::TypedVariable<32, uint32_t, ::ComponentVariables::Variable1>, // FCursorPos
  2 // Rows
   > _o_LiquidCrystalDisplay1;

Mitov::LiquidCrystalElementTextField<
    Mitov::LiquidCrystalDisplay<
      Mitov::LiquidCrystalDisplayParallel<
      Mitov::LiquidCrystalDisplayParallel4DataPins<Mitov::DigitalPin_DirectBoardPinImplementation<4 >, Mitov::DigitalPin_DirectBoardPinImplementation<5 >, Mitov::DigitalPin_DirectBoardPinImplementation<6 >, Mitov::DigitalPin_DirectBoardPinImplementation<7 >>, // 1_PINS
      Mitov::DigitalPin_DirectBoardPinImplementation<8 >, // 1_PINS_0
      Mitov::DigitalPin_NoImplementation<1 >, // 1_PINS_1
      Mitov::DigitalPin_DirectBoardPinImplementation<9 >, // 1_PINS_2
      Mitov::ConstantProperty<21, bool, false >, // AutoScroll
      Mitov::ConstantProperty<24, bool, false >, // Blink
      Mitov::ConstantProperty<20, bool, true >, // Enabled
      Mitov::ConstantProperty<25, bool, false >, // Hight10Pixels
      Mitov::ConstantProperty<22, bool, false >, // RightToLeft
      Mitov::ConstantProperty<23, bool, false > // ShowCursor
      >, // 0_TYPE
      16, // Columns
      Mitov::TypedVariable<38, uint32_t, ::ComponentVariables::Variable2>, // FCursorLine
      Mitov::TypedVariable<32, uint32_t, ::ComponentVariables::Variable1>, // FCursorPos
      2 // Rows
       >, // 0_TYPE_OWNER
    Declarations::_o_LiquidCrystalDisplay1, // 1_NAME_OWNER
    Mitov::ConstantProperty<5, bool, true >, // AllignLeft
    Mitov::ConstantProperty<7, uint32_t, 0 >, // Column
    Mitov::ConstantProperty<6, char, ' ' >, // FillCharacter
    Mitov::ConstantPropertyString<3, ::VisuinoConstants::TextValue0 >, // InitialValue
    Mitov::ConstantProperty<8, uint32_t, 0 >, // Row
    Mitov::ConstantProperty<4, uint32_t, 16 > // Width
     > TArduinoLiquidCrystalElementTextField1;

} // Declarations

namespace ComponentsHardware
{
void SystemUpdateHardware()
{
}
} // ComponentsHardware

//The setup function is called once at startup of the sketch
void setup()
{
  Declarations::_o_LiquidCrystalDisplay1.SystemInit();
  Declarations::TArduinoLiquidCrystalElementTextField1.SystemStart();

  OpenWire::SystemStarted();
}

// The loop function is called in an endless loop
void loop()
{
}
